# springdoc-openapi项目配置
springdoc:
  api-docs:
    enabled: false
    groups:
      enabled: false
  packages-to-scan: com.example.kernel

knife4j:
  enable: false
  setting:
    language: zh_cn
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: deleted_time # 全局逻辑删除字段名
      logic-delete-value: "datetime('now', 'localtime')" # 逻辑已删除值
      logic-not-delete-value: "null" # 逻辑未删除值

spring:
  jmx:
    enabled: false
  main:
    lazy-initialization: true