server:
  port: 25566
  address: 127.0.0.1 # 监听地址 [127.0.0.1 仅本地访问 / 0.0.0.0 所有均可访问 / other 网卡地址]

spring:
  application:
    name: kernel
  profiles:
    active: dev

path:
  workspace:
  data:
  log:
