# springdoc-openapi项目配置
springdoc:
  api-docs:
    enabled: false
    groups:
      enabled: false
  packages-to-scan: com.example.kernel

# knife4j的增强配置
knife4j:
  enable: false
  setting:
    language: zh_cn
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md

# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl