server:
  port: 25566
  address: 127.0.0.1 # 监听地址 [127.0.0.1 仅本地访问 / 0.0.0.0 所有均可访问 / other 网卡地址]

spring:
  application:
    name: kernel
  profiles:
    active: prod

base:
  boot:
    system:
      path:
        workspace: workspace
      async:
        thread-name-prefix: async-
        core-pool-size: 5
        max-pool-size: 50
        keep-alive-seconds: 60
        queue-capacity: 10000