/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    Breadcrumb: typeof import('./src/components/common/Breadcrumb.vue')['default']
    MessageComponent: typeof import('./src/components/Message/MessageComponent.vue')['default']
    ModuleSection: typeof import('./src/components/ModuleSection.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    OverviewCard: typeof import('./src/components/OverviewCard.vue')['default']
    QuickAccessCard: typeof import('./src/components/QuickAccessCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
  }
}
